AWS_ACCOUNT_NUMBER_OF_DIGITS = 12
AWS_ACCOUNT_NUMBER_OF_DIGITS_TO_MASK = 8
MASK_CHAR = 'X'
AT_CHAR = "@"
EMAIL_VALIDATE_PATTERN = r"^\S+@\S+\.\S+$"
EMAIL_MASKING_FROM_INDEX = 3
EMAIL_NUMBER_OF_MASKED_CHARS = 3
